In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124
2.6.0+cu124


#Creating tensor

In [3]:
#scalar

scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as Python int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
#tensor
tensor=torch.tensor([[[1,2,3],
 [3,6,9],
  [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#Random tensors

In [17]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2295, 0.8531, 0.3394, 0.6305],
        [0.2121, 0.7607, 0.1502, 0.1656],
        [0.9700, 0.1721, 0.1670, 0.5484]])

In [18]:
random_tensor.ndim

2

In [19]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
torch.rand(size=(3,3))

tensor([[0.5427, 0.8838, 0.6586],
        [0.2221, 0.9730, 0.1133],
        [0.8588, 0.6532, 0.2487]])

#Zeros and ones

In [21]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

#Create a range of tensors and tensors-like

In [26]:
one_to_ten=torch.arange(start=0,end=1000, step=125)
one_to_ten

tensor([  0, 125, 250, 375, 500, 625, 750, 875])

In [27]:
torch.__version__

'2.6.0+cu124'

In [28]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatypes

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device="cpu",
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor* float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
inr_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
inr_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
float_32_tensor*inr_32_tensor

tensor([ 9., 36., 81.])

In [35]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4129, 0.8755, 0.4824, 0.4666],
        [0.1671, 0.1172, 0.3282, 0.4301],
        [0.3824, 0.2042, 0.0268, 0.9876]])

In [36]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Devise tensor is on: {some_tensor.device}")

tensor([[0.4129, 0.8755, 0.4824, 0.4666],
        [0.1671, 0.1172, 0.3282, 0.4301],
        [0.3824, 0.2042, 0.0268, 0.9876]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Devise tensor is on: cpu


#Manipulating Tensors

In [37]:
tensor = torch.tensor([1,2,3])
tensor *10

tensor([10, 20, 30])

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
tensor+111

tensor([112, 113, 114])

In [40]:
tensor-12

tensor([-11, -10,  -9])

In [41]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor,10)

tensor([11, 12, 13])

#Matrix multipication

In [43]:
print(tensor, "*", tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
tensor

tensor([1, 2, 3])

In [46]:
1*1 +2*2 + 3*3

14

In [47]:
tensor @ tensor

tensor(14)

In [48]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
  print(value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 2.24 ms, sys: 30 µs, total: 2.27 ms
Wall time: 13 ms


In [49]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 72 µs, sys: 9 µs, total: 81 µs
Wall time: 84.6 µs


tensor(14)

In [51]:
tensor_A= torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B= torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [52]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [55]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [56]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [57]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [59]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [74]:
x=torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [75]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [76]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [77]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [66]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [78]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
x.argmin()

tensor(0)

In [69]:
x[0]

tensor(0)

In [79]:
x.argmax()

tensor(9)

In [80]:
x[9]

tensor(90)

In [81]:
x=torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [84]:
x_reshaped=x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [85]:
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [86]:
z[:, 0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [89]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [90]:
x_reshaped.shape

torch.Size([9, 1])

In [92]:
x_reshaped.squeeze().shape

torch.Size([9])

In [107]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)
print(f"w: {x_original.shape}")
print(f"ww: {x_permuted.shape}")

w: torch.Size([224, 224, 3])
ww: torch.Size([3, 224, 224])


In [108]:
print(type(x_original))


<class 'torch.Tensor'>


In [109]:
x_original[0, 0, 0] = 728218
print(x_original[0, 0, 0], x_permuted[0, 0, 0])


tensor(728218.) tensor(728218.)


#Indenxing

In [110]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [111]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [113]:
x[0][0]

tensor([1, 2, 3])

In [114]:
x[0][0][0]

tensor(1)

In [116]:
x[0][1][1]

tensor(5)

In [117]:
x[:, 0]

tensor([[1, 2, 3]])

In [118]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [121]:
x[:, 1, 1]

tensor([5])

In [122]:
x[0, 0, :]

tensor([1, 2, 3])

#Reproducbility

In [124]:

random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)


tensor([[0.4869, 0.4609, 0.2271, 0.8286],
        [0.2043, 0.9094, 0.0022, 0.1984],
        [0.6523, 0.1716, 0.6935, 0.5518]])
tensor([[0.2232, 0.2994, 0.9099, 0.0988],
        [0.1053, 0.0637, 0.0986, 0.8375],
        [0.9015, 0.1249, 0.2799, 0.1828]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [126]:
RANDOM_SEED =42

torch.manual_seed(RANDOM_SEED)
random_tensor_C =torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D =torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#Accesising a GPU

In [2]:
!nvidia-smi

Thu Jun 19 18:58:21 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   56C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
import torch
torch.cuda.is_available()

True

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
torch.cuda.device_count()

1

In [8]:
tensor=torch.tensor([1, 2, 3], device="cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [10]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

#Exercises

In [2]:
import torch
torch.rand(7, 7)

tensor([[0.1896, 0.8827, 0.7420, 0.6733, 0.0580, 0.0708, 0.8005],
        [0.7997, 0.2379, 0.8584, 0.6602, 0.4433, 0.1624, 0.4357],
        [0.1743, 0.6363, 0.7778, 0.5732, 0.3906, 0.7829, 0.6401],
        [0.9026, 0.8360, 0.9567, 0.6331, 0.6361, 0.6433, 0.0936],
        [0.1095, 0.2428, 0.5894, 0.0246, 0.1735, 0.2384, 0.5092],
        [0.1812, 0.5041, 0.5519, 0.6774, 0.5896, 0.9189, 0.4254],
        [0.7148, 0.3947, 0.6320, 0.0511, 0.9631, 0.8436, 0.2377]])